### ISSUE TITLE
prodiguer-reformatter et les valeurs "null"

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#11]
Commentaire de Jérôme Servonnat
 - @Mark: après un peu d'utilisation des résultats reformattés, il s'avère que les valeurs 'null' (non renseignées) font que certaines simulations qui ne sont pas entièrement décrites peuvent ne pas s'afficher sur les tableaux ; j'ai fait un essai de remplacer les null par des '--' (avec une commande sed sur les fichiers reformatés) et mes simulations qui ne s'affichaient pas sont maintenant visibles sur le tableau. Que penses-tu du fait de changer les null par une chaîne de caractères explicite ('--' donne un rendu propre et clair sur les tableaux de métriques)?

**Comment by momipsl** [comment]
A mon avis c'est la responsabilté de l'UI de faire un parse sur les resultats reformattés avant de remplir les tableaux.
