### ISSUE TITLE
skip or overwrite mode to prodiguer-metric-add-batch (default should be skip)

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#12]
Commentaire de Jérôme Servonnat
- @Mark: nous avions parlé d'une fonctionnalité de vérification de l'existant pour l'alimentation de la base, qui ferait:
     * une vérification des résultats présents sur la collection
     * si des résultats de métriques correspondants aux résultats de la simulation que l'on veut déposer sont déjà sur la base, l'utilisateur a la possibilité de 'skip' ou 'overwrite'
Cette fonctionnalité est de plus en plus nécessaire avec l'augmentation du nombre de métriques déposées dans la base. Si c'est possible pour toi, je pousserais bien un peu pour que cette fonctionnalité devienne prioritaire dans le chantier métriques... on pourra rediscuter un peu de la manière optimale (pour l'utilisateur) de faire cette fonctionnalité (quels champs vérifier...)

**Comment by momipsl** [comment]
This requires creating a hash id for each metric block.  The hash id is based upon the masking, simulation, regridding, reference & variable information associated with the metric block.  If the hash id already exists in the Mongo db then the existing record is overwritten if the metrics have changed otherwise it is skipped.

**Comment by SebastienDenvil** [comment]
To be clear on the workflow I want to remind that the skip decision should be the default decision if hash_id already exists in the Mongo db. To change that user will have to enforce the mechanism by activating a "force" option like "-f" or "--force".

**Comment by momipsl** [comment]
So I will add a new input parameter to the prodiguer-metric-add command: force=true/false

**Comment by momipsl** [comment]
OK so I have updated the prodiguer-metric-add server side implementation.  For each metric set being uploaded a hash is calculated based upon the group id and the metric set itself.  When inserting the metric set into the MongoDB, a DuplicateRecord exception is raised if the hash is already in use.  

I think that there is no necessity to have skip / force options as if the hash of the record being inserted is already in use it means that the metric set has already been inserted.   I.E. why would you need to force a duplicate record ?  But perhaps I am not understanding some nuance of the use case.

As there are existing groups in the database I guess there may be a need for a 'set-hashes' command to apply hashes to existing records.  Alternatively simply delete the existing collections and reupload.

**Comment by SebastienDenvil** [comment]
1. I think there is a misunderstanding on what should be use to generate the hash. We decided on that in my office during your last visit but that would be good to check here. We listed the list of attributes to consider to generate the hash. If you included (as I think you did) the creation date in the bundle of parameter used to generate the hash then the hash will always be different. Creation date must be discarded for hash generation.
Example
"ModellingGroup"
"ModelFreeSpace"
"MIPTable": "Amon"
"ModelActivity"
"Experiment"
"Model"
"SimName"
"period"

2. We do need the skip/force behaviour. We will need to re-inject metrics during metrics development when code adjustments or bug correction occur. Very important : we don't want duplicate record. We want to have full control on the following decision : do I replace a given metric by another or not. And I don't want to replace it accidentally, so we have the force option.

**Comment by momipsl** [comment]
OK will push hashed generation into the formatter based upon a configurable subset of fields that excelled the metrics themselves and timestamp related fields.  Will do this today.

**Comment by SebastienDenvil** [comment]
Great we will be good to go then

**Comment by jservonnat** [comment]
To confirm what Seb said, here is a detailed, official, way that we would like this check to work.
First, the check is done on the values of the following keywords:
        "maskingRegion"
        "maskingValue"
        "referenceFileCheckSum"
        "referenceFilename"
        "referenceName"
        "referencePeriod"
        "referenceTrackingDate"
        "referenceType"
        "regriddingGridName"
        "regriddingMethod"
        "regriddingTool"
        "simulationActivity"
        "simulationComputeNode"
        "simulationCreationDate"
        "simulationExperiment"
        "simulationFreeSpace"
        "simulationInputClimatologyFileCheckSum"
        "simulationInputClimatologyFileName"
        "simulationInstitute"
        "simulationLogin"
        "simulationMIP"
        "simulationModel"
        "simulationName"
        "simulationPeriod"
        "simulationTrackingID"
        "variable"
Those fields are already available in the json files.
We talked this morning with Seb about adding:
"simulationCheckSum" => md5 sum of the input file
"metricCreationDate" => date of execution of the Metrics Package (when it calls the param file)
Both can be added easily from the parameter file.

Then, if one record in the collection already matches the values of those keywords (for the block of metrics that we are trying to put in the collection), then:
- by default, skip
- alternatively, we can force replacing the existing record in the collection with the metric that we are trying to put in the database.

**Comment by prodiguer-git-user** [comment]
OK thanks for the clarification.  I am in the process of implementing this as well as adding a timestamp to be applied to all metrics uploaded as part of the same batch.

**Comment by momipsl** [comment]
Have updated the metrics-formatter so that it injects 2 fields: _formatting_timestamp; _hashid.  Note that the fields are prefixed with an underscore (_) to indicate that they are control fields injected by the formatter.  

The fields to be included in the hash-id calculation are defined in the [hash_fieldset.config](https://github.com/Prodiguer/prodiguer-metrics-formatter/blob/master/metrics_formatter/hash_fieldset.config) file.

I will now need to extend the metrics-add command so as to implement the skip / force paradigm.

**Comment by jservonnat** [comment]
@momipsl : also, I've added the "simulationCheckSum" and "metricCreationDate" keywords to the json files. Can you add them in the reformatting so we find them afterwards in the reformatted json files?
Many thanks!

**Comment by prodiguer-git-user** [comment]
Are these fields added to the SimulationDescription or are they simply appended to the end of the file ?

**Comment by jservonnat** [comment]
In the SimulationDescription block.

**Comment by momipsl** [comment]
Just a note to say that name of the computed metric hash field has changed.  Previously it was "_hashid", now it is simply "_id".  The reason is that "_id" conincides with the default primary key given to records by MongoDB.  Therefore we can take advantage of the default collection index over this key and thus do not need to create a second collection index.  This streamlines the solution in terms of lines of code and also reduces db size as only one index needs to be maintained.

**Comment by jservonnat** [comment]
@momipsl can you confirm that simulationCheckSum and metricCreationDate are not yet in the reformatter? (today)
If not, when do you think this should be available (this to avoid putting metrics on the database in collections that will become obsolete soon)?
Thanks!

**Comment by momipsl** [comment]
Just committed necessary changes.  Execute the following command to update the formatter on the server: **prodiguer-stack-update-repo prodiguer-metrics-formatter**

**Comment by jservonnat** [comment]
Thank you Mark.
I just executed the command but apparently there is an error:
[esg-user@prodiguer-test-web ~]$ prodiguer-stack-update-repo prodiguer-metrics-formatter
-bash: prodiguer-stack-update-repo : commande introuvable
Any thought?

**Comment by SebastienDenvil** [comment]
I ran it as root. The command name is prodiguer-stack-update-repos (with a s)

And actually all the repos has been updated which is not the expected behaviour.

prodiguer-stack-update-repos prodiguer-metrics-formatter
IPSL PRODIGUER INFO SH > Updating repo: prodiguer-cv
Unpacking objects: 100% (5/5), done.
IPSL PRODIGUER INFO SH > Updating repo: prodiguer-docs
IPSL PRODIGUER INFO SH > Updating repo: prodiguer-fe
Unpacking objects: 100% (6/6), done.
IPSL PRODIGUER INFO SH > Updating repo: prodiguer-metrics-formatter
Unpacking objects: 100% (5/5), done.
IPSL PRODIGUER INFO SH > Updating repo: prodiguer-server
-------------------------------------------------------------------------------

**Comment by momipsl** [comment]
FYI you can also update each individual repo with the prodiguer-stack-update-repo REPO_NAME command.  If it is not available then brodiguer-stack-update-shell && source /opt/prodiguer/exec.alias prior to trying again.

**Comment by SebastienDenvil** [comment]
Trust me when I say there is currently no **prodiguer-stack-update-repo** command available.... anyhow ... https://github.com/Prodiguer/prodiguer-shell/blob/master/exec.aliases

**Comment by jservonnat** [comment]
@momipsl I wanted to say that the inclusion of this skip function will change my life ;). Many thanks!

**Comment by SebastienDenvil** [comment]
@jservonnat Have you checked it behaves as expected? Can we close this issue?

**Comment by jservonnat** [comment]
I haven't been able to check it properly (by using the Metrics Garden) but we will do this tomorrow.
