### ISSUE TITLE
only display monitoring end points when they exist

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#15]
libIGCM will have to send a message stating that this link (for example) exist

https://esgf.extra.cea.fr/thredds/fileServer/WORK/p86mart/IPSLCM6/DEVT/piControl/OR11V01/MONITORING/index.html

**Comment by momipsl** [comment]
This seems to require a specific message type.  Perhaps 6000.

**Comment by SebastienDenvil** [comment]
I would like to avoid adding a new message for this. This link will exist if (at least) one postprocessing job having postProcessingName=monitoring is successful on the TGCC or IDRIS center.

message=2000+message=2100+postProcessingName=monitoring

Does it sound its doable within the current framework?

**Comment by momipsl** [comment]
This should be feasible ... will verify
