### ISSUE TITLE
Cascading on the UI is mandatory.

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#16]
When selecting a value for a facet the other facets must be updated accordingly so as not the end up with a null "query".

**Comment by momipsl** [comment]
Just committed initial implementation of this.  Still need to do further testing when a new CV term is recieved by front-end in response to a new simulation with new cv terms.

**Comment by momipsl** [comment]
This is now ready for testing.  However it has introduced a new issue related to changing activity: if activity=IPSL and experiment=IPSLCM5A then this means that activity=CMIP5 is unavailable to select as there are no CMIP5 simulations with this experiment (i..e it would produce a null result).  I think that changing activity should always be possible and that doing so resets the other filters.  Please confirm whether activity should indeed be considered a "root filter"

**Comment by SebastienDenvil** [comment]
You mean activity=IPSL and model=IPSLCM5A?

Ready for testing means I can make a deployment?

And for now no need to introduce a special case for activity. It looks confusing to me to introduce a special behaviour for a facet. Some model will appear in different activity and that's precisely what the faceted search have to exhibit.

**Comment by momipsl** [comment]
Yes ready to deploy.  We can discuss this issue next week and decide then if we wish to add a special behaviour for activity.
