### ISSUE TITLE
Monitoring front-end paging when large number of pages

### ISSUE THREAD

**Issue by momipsl** [Prodiguer/prodiguer-docs#17]
When there are alot of simulations to be displayed (>200) the rendering of the paging buttons is ugly.  Need to simplify rendering.

**Comment by momipsl** [comment]
New pager has been implemented.  This allows user to navigate to first, next, previous and last pages.  It also allows user to enter a page number directly.

**Comment by SebastienDenvil** [comment]
That's much better! thanks
