### ISSUE TITLE
Link to monitoring pages from simulation monitor page

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#2]
IDRIS server:
https://prodn.idris.fr/thredds/fileServer/IDRISPUBFS

TGCC server:
https://esgf.extra.cea.fr/thredds/fileServer/DODSWORK

Examples, server address to be adapted for each center:
https://prodn.idris.fr/thredds/fileServer/IDRISPUBFS/rces311/IPSLCM5A/PROD/abruptO3/abruptO3MRM1/MONITORING/index.html

https://prodn.idris.fr/thredds/fileServer/IDRISPUBFS/LOGIN/MODEL/SPACENAME/EXPERIMENT/SIMULATIONNAME/MONITORING/index.html

**Comment by momipsl** [comment]
Added links to both monitoring and inter-monitoring.  Need to review inter-monitoring link as I am not sure if this application is maintained anymore.
