### ISSUE TITLE
UI color code and rollback

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#20]
ROLLBACK color code is not described in the legend. It appears in white in the UI.

Also what is the condition to be in the "ROLLBACK" state?

QUEUED RUNNING COMPLETE ERROR should be enough for now.

**Comment by momipsl** [comment]
Latest version has only these 4 states.

**Comment by SebastienDenvil** [comment]
I run the latest version of the UI. And I still have ROLLBACK in the facets and white entries in the simulation list. I suppose we have to update tables in the DB.

I would prefer to close this issue when it's fix on the deployed system.

**Comment by momipsl** [comment]
To test this you will need to update source code on web server so as ti pull latest front end changes and then possibly refresh your browser cache (alternatively restart nginx which causes cache headers to be regenerated)..

**Comment by SebastienDenvil** [comment]
Yes that's what I did.
