### ISSUE TITLE
regression managing new CV terms

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#21]
A regression occured on the "monitoring system". To reproduce you could try to ingest recent message from AMPQ-PROD-PROCESSED
Dozens of simulations sent the 0000 message but only a few are displayed. Message with attachments have a 0000 message.

It seems to me that new CV terms are not added and managed. Behaviour changed compared to what it was just before I made the upgrade to fix the ext-smtp-realtime.

in-monitoring_01-stdout---supervisor-LwtP52.log:2015-03-10T10:40:30.171114+00:00 :: IPSL PRODIGUER ERROR MQ > <class 'prodiguer.cv.exceptions.TermNameError'> :: Unknown CV term :: compute_node_login.rlmd309.
in-monitoring_01-stdout---supervisor-LwtP52.log:2015-03-10T11:31:28.299471+00:00 :: IPSL PRODIGUER ERROR MQ > <class 'prodiguer.cv.exceptions.TermNameError'> :: Unknown CV term :: compute_node_login.rlmd309.
in-monitoring_01-stdout---supervisor-LwtP52.log:2015-03-10T11:53:13.245904+00:00 :: IPSL PRODIGUER ERROR MQ > <class 'prodiguer.cv.exceptions.TermNameError'> :: Unknown CV term :: compute_node_login.rlmd309.
in-monitoring_01-stdout---supervisor-LwtP52.log:2015-03-10T13:27:43.128224+00:00 :: IPSL PRODIGUER ERROR MQ > <class 'prodiguer.cv.exceptions.TermNameError'> :: Unknown CV term :: compute_node_login.rlmd981.
in-monitoring_01-stdout---supervisor-LwtP52.log:2015-03-10T15:10:40.413228+00:00 :: IPSL PRODIGUER ERROR MQ > <class 'prodiguer.cv.exceptions.TermNameError'> :: Unknown CV term :: compute_node_login.rlmd981.
in-monitoring_01-stdout---supervisor-LwtP52.log:2015-03-10T21:49:22.352780+00:00 :: IPSL PRODIGUER ERROR MQ > <class 'prodiguer.cv.exceptions.TermNameError'> :: Unknown CV term :: compute_node_login.rlmd309.
in-monitoring_01-stdout---supervisor-LwtP52.log:2015-03-10T21:57:49.017008+00:00 :: IPSL PRODIGUER ERROR MQ > <class 'prodiguer.cv.exceptions.TermNameError'> :: Unknown CV term :: compute_node_login.rlmd309.
in-monitoring_01-stdout---supervisor-LwtP52.log:2015-03-10T22:08:21.474489+00:00 :: IPSL PRODIGUER ERROR MQ > <class

**Comment by momipsl** [comment]
OK I have now been able to replicate this in my environment.  The issue was caused when setting the display name for new CV terms.  A flag telling the CV parser not to raise an error if the term name does not exist was not being passed.  

Ready to retest.
