### ISSUE TITLE
Rules for the state property

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#22]
receiving 0000 or 1000 means RUNNING
receiving 9999 means ERROR
receiving 0100 means COMPLETED
receiving 1100 but not 0100 means QUEUED

**Comment by momipsl** [comment]
I have now implemented these changes on both back and front ends.  This will require a system reset as changes have been made in front-end, database and mq consumers.

**Comment by SebastienDenvil** [comment]
None of the simulation reached the completed state over the week end.

You can test using email coming from me in the AMQP-PROCESS folder. There are 2 simulations.

**Comment by momipsl** [comment]
OK will test now.

**Comment by momipsl** [comment]
Just committed a patch in front-end to correctly derive simulation state even if a 1100 message is received after a 0100 or 9999.

**Comment by SebastienDenvil** [comment]
have you observed a 1100 message being sent after a 9999 message?

if a 9999 message is received the status must be "ERROR"

**Comment by momipsl** [comment]
I believe that the system is fine in this scenario.  The db table tbl_simulation_status will correctly contain 2 entries: one for the 9999 message and one for the 1100 message.  However the derived status will be ERROR.

**Comment by SebastienDenvil** [comment]
Sorry I was not clear. What I meant is that it must be impossible to receive 1100 and 9999 coming from the same email bundled. If it has been observed it is a libIGCM bug.

It is possible to receive a 9999 message. Then after some correction the simulation will send 1000 then 1100 and hopefully a 0100 at some point.

**Comment by momipsl** [comment]
I have not observed 1100 & 9999 in same email bundle.  

However I assumed that a 9999 indicates a simulation termination.  If you are saying that a correction results in a subsequent flow of 1000 / 1100 and finally a 0100 then I need to verify that the front-end will correctly handle this scenario.

**Comment by SebastienDenvil** [comment]
No. 9000 are sent each time something wrong occurred during a simulation. But anyway a 9999 will be sent. Corrective actions are taken and the simulation try to run again (sending a 1000). If it was successful the simulation will continue as it should (1000, 1100, 1000, 1100, 0100). If it was not successful then back to 9999 (with many 9000 before in the same bundle).

9999 is not equivalent to simulation termination.

**Comment by momipsl** [comment]
OK I will review current implementation and remove this assumption from derivation of current execution state that is done in the UI.  

It might be a good idea at some point to document expected message type flows for a normal simulation; a 'corrected' simulation; a failed simulation.

**Comment by SebastienDenvil** [comment]
This is still valid to define state of simulations. See the beginning of this issue. I put it back here.
https://github.com/Prodiguer/prodiguer-docs/wiki/Monitoring

receiving 0000 or 1000 means RUNNING
receiving 9999 means ERROR
receiving 0100 means COMPLETED
receiving 1100 but not 0100 means QUEUED

**Comment by SebastienDenvil** [comment]
Running state is never used by the current UI. Mark could you point me the code base taking this in charge? We need to have this information right.

**Comment by momipsl** [comment]
This is derived in the front end code [here at line 24](https://github.com/Prodiguer/prodiguer-fe/blob/master/src/js/monitoring/utils.parser.js).  The logic is as follows: If the simulation has not ended and there is a running job then the simulation is in the running state.  I will verify that this is being correctly assigned.  If so then the issue is actually a CSS one which will be very simply to correct.  

Await feedback.

**Comment by momipsl** [comment]
Have checked in a commit that ensures the derivation of current simulation state is correct.  This bug was caused by checking for undefined instead of null in the relevant javascript function.

**Comment by SebastienDenvil** [comment]
Done
