### ISSUE TITLE
Must push new CV terms in between db-resets

### ISSUE THREAD

**Issue by momipsl** [Prodiguer/prodiguer-docs#23]
Need to include within the operational workflow so that before executing a prodiguer-db-reset the new cv terms are pushed to GitHub.

**Comment by momipsl** [comment]
New commands have been added to begin addressing this issue:  prodiguer-cv-git-pull, prodiguer-cv-git-push, prodiguer-cv-git-setup.  I have also created a new GitHub user account called prodiguer-git-user which is used by the prodiguer system for automated git interaction scenarios such as this one.

Upon the MQ server you will need to:

1.  Add the following to the ops/config/prodiguer.sh file:
        # Username of GitHub account used to push changes to GitHub.
        declare GIT_USERNAME=prodiguer-git-user
        
       # Email of GitHub account used to push changes to GitHub.
       declare GIT_EMAIL=mark.morgan@ipsl.jussieu.fr

2. Update the shell.

3.  Execute prodiguer-cv-git-setup  - which should prompt for the password for the new prodiguer-git-user account (see same password used for db).

4.  Execute prodiguer-git-cv-push - which will push new cv terms to prodiguer-cv GitHub repo.

Next time you run prodiguer-db-reset on the DB server, execute prodiguer-git-cv-pull and then run the reset.

**Comment by momipsl** [comment]
I have amended the prodiguer-db-reset command so that it implicitly calls prodiguer-cv-git-pull prior to rebuilding the database.

**Comment by SebastienDenvil** [comment]
It seems that we also have to push new CV terms regularly. Because the UI do not always reflect new terms. Is that correct that we have regularly to:
1. push new CV terms
2. update CV on the front-end machine

**Comment by momipsl** [comment]
The issue here is that the new CV terms need to be pushed BEFORE running a db-reset so that the new DB is built with those terms.  Otherwise those terms will not find their way to the UI.  The reasons is that when a new simulation is processed on the MQ server, the job looks in prodiguer-cv to see if the term has already been created, if so then it does not write it to DB and push to UI.   

Perhaps this behaviour could be altered to that all the terms related to a new simulation are always pushed to the UI even if they have already been created in prodiguer-cv.

**Comment by SebastienDenvil** [comment]
No we can't db-reset each time a new term comes in. Need to find another solution.

**Comment by momipsl** [comment]
IT is not a question of db-reset each time a new term comes in - it is a question of synching the new terms with the prodiguer-cv repo prior to performing a db-reset.

**Comment by momipsl** [comment]
OK I ran some tests and I agree that there is an issue here.  The new terms are being perssisted to file system and the db.  However the UI is not being updated as expected.

**Comment by momipsl** [comment]
So on further analysis the issue here is when new cv terms are not pushed to the GitHub Repo and a db-reset is subsequently executed.  When a new simulation then arrives that has CV terms on the local repo not pushed to the remote repo then these terms will not be pushed to the dB / UI.  I will make a change to remove the check that says "only push to db / ui when the term was not on the local cv repo."

**Comment by SebastienDenvil** [comment]
Sorry but it is not clear to me. When you write : "push to dB/UI" it doest not imply db-reset?

Do we agree on the following:
1. we want new CV terms readily available from the UI.
2. we don't want to "db-reset" to enable 1.

**Comment by momipsl** [comment]
Yes 1. & 2. are certainly the objectives.  As new terms arrive they need to be pushed to local prodiguer-cv repo; database; & front-end.  However at present we are not pushing new cv terms to remote prodiguer-cv repo and thus they are not available to subsequent executions of db-reset.  After a db-reset, if the same term arrives again then because it already exists in the local prodiguer-cv repo it is not pushed upstream to the "new" db and ui.  This is the source of the issue.

The solution is twofold:
1.  Put a message on the MQ:  push-new-cv-term-to-remote-repo.
2.  Push terms upstream even if they are already on the local file system.

**Comment by SebastienDenvil** [comment]
What do you mean by "2. Push termes upstream"?

**Comment by SebastienDenvil** [comment]
All good as far as I can tell
