### ISSUE TITLE
Number of displayed simulations

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#24]
When selecting activity=CMIP5 the UI mentionned : Displaying 47 of 215 simulations.

Should be Displaying 20 of 47 simulations.

There are 20 simulations displayed over 47 simulations in total within the CMIP5 activity.

Same issues appear when you select activity=ipsl for instance

**Comment by momipsl** [comment]
I will update this so that it says:  Total Simulations = X.  Filtered simulations = Y.

**Comment by momipsl** [comment]
This has been implemented and is ready for deployment.  Test now reads: "Total simulation count = X. Filtered simulation count = Y."
