### ISSUE TITLE
Simulations with missing CV related fields 

### ISSUE THREAD

**Issue by momipsl** [Prodiguer/prodiguer-docs#25]
Some 0000 messages have been observed with empty values in CV related fields such as Experiment, Model ...etc.  What should happen in these scenarios ?  Should the simulation be rejected or accepted.  If accepted should the empty value be replaced with a default such as UNKNOWN ?

**Comment by SebastienDenvil** [comment]
I need to see examples of this to understand what we should do in that case

-- 
Sébastien Denvil
IPSL, Pôle de modélisation du climat
UPMC, Case 101, 4 place Jussieu,
75252 Paris Cedex 5

Tour 45-55 2ème étage Bureau 209
Tel: 33 1 44 27 21 10
Fax: 33 1 44 27 39 02

**Comment by SebastienDenvil** [comment]
Very old configurations don't have value for Space and Experiment. As you suggested they should be replace with a default value such as UNSPECIFIED or N/A. I prefer UNSPECIFIED in this case.
