### ISSUE TITLE
We need a 'set-hashes' command to apply hashes to existing records

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#26]

**Comment by momipsl** [comment]
OK will implement this today

**Comment by momipsl** [comment]
So this is implemented.  The command syntax is: prodiguer-metric-set-hashes GROUP-ID.

On the server side the metrics are retrieved from the database and the hash identifiers either assigned or reassigned.  Reassignment is necessary if the set of hash fields changes.
