### ISSUE TITLE
When we insert a metric in mongoDB do we attach an ingestion timestamp that we can further query?

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#27]
When we insert a metric in mongoDB do we attach an ingestion timestamp that we can further query?

**Comment by momipsl** [comment]
@SebastienDenvil said "When we insert a metric in mongoDB do we attach an ingestion timestamp that we can further query?".

Not at present.  If this is a requirement then it can of course be implemented.  Best to set this in the formatter as this is where the hash-id will also be generated, i..e a formatted timestamp that is identical for all the formatted metrics.  If this is done on the server side then you have the problem that the timestamp has to be returned to the client and the formatted metrics updated.

**Comment by momipsl** [comment]
A new field has been added: _formatting_timestamp.  Thus when formatting a batch of metrics all the metrics in the batch will have the same formatting timestamp.  The field is prefixed with an underscore to indicate that it is an injected field.
