### ISSUE TITLE
Food for thought on a mongoDB backup strategy

### ISSUE THREAD

**Issue by jservonnat** [Prodiguer/prodiguer-docs#29]
Patrick has pointed out this question of having a backup of the database. Here are some links he has found:

http://docs.mongodb.org/manual/core/backups/#backup-with-mongodump

Un exemple:
https://github.com/micahwedemeyer/automongobackup
ou plus simple:
https://sheharyar.me/blog/regular-mongo-backups-using-cron/

To be discussed!

**Comment by ncaripsl** [comment]
We will rely here on the ISIS team VM backup policy
