### ISSUE TITLE
Are input-format=ipsl-extended and output-format=lines still required ?

### ISSUE THREAD

**Issue by momipsl** [Prodiguer/prodiguer-docs#30]
@jservonnat The metrics-formatter requires 2 parameters: **input-format**=*pcmdi | ipsl-extended*;  **output-format**=*blocks | lines*.  

Is support of the input-format *ipsl-extended* still required ?  Is support of the output-format *lines* still required ?  If not then I would prefer to simplify the code base and remove the obsolete code.

**Comment by momipsl** [comment]
Another potentially obsolete feature is support for upload of CSV files.  This in my view should definitely be deprecated.

**Comment by jservonnat** [comment]
@momipsl I think you can put the ipsl-extended and lines aside for the moment. Maybe we will have to use ipsl-extended later on but not for the moment. And afterwards we have clearly identified that the lines format will be too heavy.
Concerning the CSV files, if we stop supporting them, will it still remain feasible in the future (if we find a particular case where it could be useful)?

**Comment by momipsl** [comment]
Re ipsl-extended and lines support: I will remove these so as to simplify code base.  Re CSV files: yes it will still be feasible in the future but I will remove the relevant code for now.

**Comment by jservonnat** [comment]
Ok so it's fine for me then.

**Comment by momipsl** [comment]
So this change has been committed.  One consequence is that the **prodiguer-metric-format** command no longer requires the INPUT-FORMAT parameter.  Usage now becomes:
'''prodiguer-metric-format GROUP-ID INPUT-DIR OUTPUT-DIR'''

**Comment by SebastienDenvil** [comment]
Will wait Jérôme to be sure his workflow is not impacted by changes in the command.
