### ISSUE TITLE
Front-end loading time is too long 

### ISSUE THREAD

**Issue by momipsl** [Prodiguer/prodiguer-docs#36]
When there are a large number of simulations in the database then the front-end loading time is way too long.  Combined with the issue related to refreshing the websocket then the front-end becomes unusable.  

Must reduce size of initial page setup data download.

**Comment by momipsl** [comment]
The initial page setup data has been split into 2 downloads: CV data; simulation data.  This allows the CV data download to be cached (via HTTP caching) separately from the simulation data, therefore download time will be reduced.  Also the simulation data is ALOT less as the tbl_simulation_state table has been deprecated.  These 2 changes combined should resolve slow page setup times.

However the search filter should perhaps be extended so as to restrict the simulations to an execution start / stop data range.  I.E. show simulations that have started in the last month, 3 months, 6 months ...etc.

**Comment by momipsl** [comment]
Also the page setup data (JSON format) is uncompressed - should switch on compression.

**Comment by SebastienDenvil** [comment]
The situation is much better now.
