### ISSUE TITLE
Update aliases for ciclad

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#38]
Those 2 should appear as IPSL-CICLAD:
ipsl-ciclad5.private.ipsl.fr
ipsl-ciclad6.private.ipsl.fr

**Comment by momipsl** [comment]
This is related to CV management.  I have created a new term for compute node machine: [IPSL-CICLAD](https://github.com/Prodiguer/prodiguer-cv/blob/master/data/compute_node_machine/ipsl-ciclad.json).  The two existing terms mentioned above (and also ipsl-ciclad8.private.ipsl.fr) can be deleted as they are now considered synonyms of the new term.  

However this will cause a problem in the front-end as it pulls terms from the database table: cv.tbl_cv_term.  Therefore the database will have to be updated.  I have created a new command: **prodiguer-db-pgres-cv-table-reset** that will do this.

Next week in Paris we will perform a CV clean up as part of the next release process.  For example there is duplication in the following cv collections: [model/tag](https://github.com/Prodiguer/prodiguer-cv/tree/master/data/model); [simulation space](https://github.com/Prodiguer/prodiguer-cv/tree/master/data/simulation_space).

**Comment by SebastienDenvil** [comment]
Done
