### ISSUE TITLE
ext-smtp-realtime will consume nearly 100% after 1 hour of operation

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#4]
After one hour of operation nothing will be consume anymore by ext-smtp-realtime from the q-ext-smtp queue and the process associated to ext-smtp-realtime consume nearly 100% of cpu

**Comment by momipsl** [comment]
Refactored code so as to close SMTP client after each server interaction.

**Comment by SebastienDenvil** [comment]
Still an issue.
"2. ext-smtp-realtime devient instable très rapidement à partir du moment où il n'y a plus de message à traiter. 5 minutes après le dernier message traité il devient instable, et ne fait plus rien. La version précédente semblait plus lente à devenir instable. On peut travailler en crontab, mais le souci c'est que dans ce cas:
- les messages qui arrivent alors que ext-smtp-realtime est instable ou en train de redémarrer ne sont pas traités.
- ext-smtp-realtime ne traite donc que les messages qui arrivent lorsqu'il est démarré et stable. Ce qui va nous poser des problèmes de robustesse."

**Comment by momipsl** [comment]
http://rainbow.chard.org/2013/02/19/thunderbird-high-cpu/  
Of course this issue is not the same as ours but does illustrate that IDLE clients can certainly consume alot of resources.  I need to understand the protocol a little more deeply.

**Comment by SebastienDenvil** [comment]
The latest deployment solved this a few weeks ago. Issue was reproducible when testing in a multi core environment. ext-smtp-realtime has been simplified. Multi threadding was removed.
see : https://github.com/Prodiguer/prodiguer-shell/commit/ad7d1e810060d55edabe3a24a2a7a9e2c65d50cb
