### ISSUE TITLE
Front end slow when rendering simulation detail / messages pages

### ISSUE THREAD

**Issue by momipsl** [Prodiguer/prodiguer-docs#48]
The front-end rendering times are extremely slow when loading the simulation detail & messages pages.  This behaviour can be replicated when running against a large test database.

**Comment by SebastienDenvil** [comment]
Simulation detail page can not be reached for some simulations:
https://prodiguer-test-web.ipsl.fr/static/simulation.detail.html?uid=339d48fa-c022-4290-8496-2caa89e837d9

Simulation detail page can be reached for others:
https://prodiguer-test-web.ipsl.fr/static/simulation.detail.html?uid=27f936db-704b-4cf9-a075-b297d4a1d743

When simulation detail can be reached like above, the message page can not be reached:
https://prodiguer-test-web.ipsl.fr/static/simulation.messages.html?uid=27f936db-704b-4cf9-a075-b297d4a1d743
