### ISSUE TITLE
Front-end security

### ISSUE THREAD

**Issue by momipsl** [Prodiguer/prodiguer-docs#50]
Due to a request from an HPC we need to restrict access to the Prodiguer front-end.  

An NGINX certificate filter plugin would be ideal as this would restrict acccess to holders of a CNRS certificate.

**Comment by momipsl** [comment]
An article outlining that this is possible: http://nategood.com/client-side-certificate-authentication-in-ngi

**Comment by momipsl** [comment]
CNRS technical article on this subject: http://www.cnrs.fr/aquitaine/spip.php?article622#mozTocId938196

**Comment by SebastienDenvil** [comment]
We will discuss with @ncaripsl before @momipsl next visit.

**Comment by SebastienDenvil** [comment]
Has been tested. Will be use when we move into production
