### ISSUE TITLE
Leverage autocomplete widgets to ease searching and filtering

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#51]
This page https://prodiguer-test-web.ipsl.fr/static/app.html would benefit a lot from this kind of widget:
https://jqueryui.com/autocomplete/

Drop down box shall be editable and benefit from the auto completion

**Comment by SebastienDenvil** [comment]
To clarify : this concerns every drop down box and the main page. Not the simulation details.

**Comment by momipsl** [comment]
This feature has been implemented & deployed.
