### ISSUE TITLE
Sortable tabular data

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#52]
Search results from here shall be sortable along any column
https://prodiguer-test-web.ipsl.fr/static/app.html?activity=ipsl

**Comment by momipsl** [comment]
Monitoring page sort columns: name, machine, acc.proj, login, model, spance, experiment

**Comment by momipsl** [comment]
Detail page sort: all columns on both grids

**Comment by momipsl** [comment]
Implemented sorting upon main monitoring page.  Have just pushed this out into test web server.

Note that the sort field is not persisted to cookie or assignable via URL query param.  Please advise if you wish me to add this so that the sort order is also 'remembered'.

**Comment by momipsl** [comment]
Have now implemented sorting of job histories upon detail page.  Also updated main montoring page to include sort field & direction in persistent URL.

**Comment by momipsl** [comment]
Updated default sort direction depending upon sort field.  Also all sort state is persisted to cookies.
