### ISSUE TITLE
Monitoring page broken link in web-socket notification panel

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#53]
The front end displays that sort of information when status changed. The simulation name is clickable but leads to the home page. This is missleading.
 2016-03-10 11:45:04 :: JOB STARTED :: TERMSNOWhighL is RUNNING

**Comment by momipsl** [comment]
This issue seems to be related to speed of incoming web-socket events.  The rendering was simplified accordingly.
