### ISSUE TITLE
 Acc. Project added in the faceted search

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#55]
For example gzi for IDRIS and gencmip6 (+ subproject when approriate)

The Acc. Project should also be one of the column here. Just after the "machine" column.
https://prodiguer-test-web.ipsl.fr/static/app.html

**Comment by momipsl** [comment]
So just to confirm this requires both a filter drop-down plus a new grid column ?

**Comment by SebastienDenvil** [comment]
Yes : this requires both a filter drop-down plus a new grid column.

**Comment by momipsl** [comment]
Any existing filters / columns that can be removed ?  I ask as adding a new one means that space becomes a little tight.

**Comment by SebastienDenvil** [comment]
Nothing obvious. Sorry.
