### ISSUE TITLE
Editable number of results per page

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#56]
Being able to choose if 25 or 50 or ... results per page are displayed.
https://prodiguer-test-web.ipsl.fr/static/simulation.detail.html?uid=9ae9b875-226a-4f98-a05f-cb57eac5911f

**Comment by momipsl** [comment]
Will add next to the pager a drop-down with the selectable values of 25 | 50.

**Comment by momipsl** [comment]
Have added page size selectors to all grids.
