### ISSUE TITLE
Intermonitoring URLs need change 

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#57]
Due to TDS v5 behaviour we need to change URL we send to the intermonitoring

"dodsC" must be replace by "catalog"

They should be:
http://esgf.extra.cea.fr/thredds/catalog/work/p86caub/IPSLCM6/TEST/piControl

And not:
http://esgf.extra.cea.fr/thredds/dodsC/work/p86caub/IPSLCM6/TEST/piControl

**Comment by momipsl** [comment]
I have updated the base URL's for inter-monitoring that are specified in the front end.  Can you please review the new settings:

https://github.com/Prodiguer/prodiguer-fe/blob/master/src/js/simulation/shared/main.js#L87-L90

**Comment by momipsl** [comment]
Also please review the base URL's for monitoring:

https://github.com/Prodiguer/prodiguer-fe/blob/master/src/js/simulation/shared/main.js#L78-L81
