### ISSUE TITLE
Monitoring page compute end date display issue

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#58]
Always the same end date here: 2016-03-08 09:52
https://prodiguer-test-web.ipsl.fr/static/app.html?activity=ipsl

The Compute start and Compute end date format are not homogenous here:
https://prodiguer-test-web.ipsl.fr/static/app.html?activity=ipsl

**Comment by momipsl** [comment]
Fixed.
