### ISSUE TITLE
Verify allocation setup file

### ISSUE THREAD

**Issue by momipsl** [Prodiguer/prodiguer-docs#59]
The [allocation initialisation file](https://github.com/Prodiguer/prodiguer-server/blob/master/prodiguer_jobs/db/run_pgres_update_conso.json) has to be updated.  

The existing MQ consumer log will be parsed in order to identify missing allocations.

**Comment by NeferTiyi** [comment]
Here is the updated file (as .txt since .json cannot be added as attachment):
[run_pgres_update_conso.txt](https://github.com/Prodiguer/prodiguer-docs/files/220802/run_pgres_update_conso.txt)

**Comment by momipsl** [comment]
I re-extracted allocations from the MQ platform log:

- [log file](https://raw.githubusercontent.com/Prodiguer/prodiguer-server/master/test-data/conso/conso-mq-log.log)
- [extractor script](https://github.com/Prodiguer/prodiguer-server/blob/master/test-data/conso/conso-mq-log.py)
- [extracted](https://github.com/Prodiguer/prodiguer-server/blob/master/test-data/conso/conso-mq-log.csv)

**Comment by slipsl** [comment]
The original file has been updated.

**Comment by slipsl** [comment]
Not taking the date into account, and after sort/unique, the new extraction leads to: 

Centre | Project | Machine | Node
------ |-------- | ------- | ----
idris  | gzi     | ada     | standard     
idris  | lmd     | ada     | standard     
idris  | omr     | ada     | standard     
idris  | psl     | ada     | standard     
tgcc   | gen0826 | curie   | hybrid       
tgcc   | gen0826 | curie   | thin/standard
tgcc   | gen2201 | curie   | fat/large    
tgcc   | gen2201 | curie   | thin/standard
tgcc   | gen2212 | curie   | thin/standard
tgcc   | gen6328 | curie   | fat/large    
tgcc   | gen6328 | curie   | thin/standard
tgcc   | gen6877 | curie   | thin/standard
tgcc   | gen7403 | curie   | thin/standard

 * `gzi` corresponds to `rgzi` in the current json file.
 * both `gen0826` lines already are in the current json file.

**Comment by momipsl** [comment]
The new allocation file will be uploaded to the db as part of the next deployment.
