### ISSUE TITLE
Front end web-socket connection is being dropped

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#6]
After 3 to 5 minutes the front-end client lost the connection with the server. The connection should be alive as long as the client is alive, or should be alive longer. Otherwise we loose the interest of the main tornado feature : real time

When the connection has been close you need to reload the front end and to reset your settings.

IPSL PRODIGUER INFO MQ > WS monitoring :: connection opened :: clients = 1.
IPSL PRODIGUER INFO API > monitoring :: on new_simulation event received
IPSL PRODIGUER INFO API > monitoring :: on new_simulation event broadcast
IPSL PRODIGUER INFO API > monitoring :: on simulation_state_change event received
IPSL PRODIGUER INFO API > monitoring :: on simulation_state_change event broadcast
IPSL PRODIGUER INFO MQ > WS monitoring :: connection closed :: clients = 0.

**Comment by momipsl** [comment]
Captured web socket close event in browser and the front-end now displays a message saying "The Prodiguer web socket server connection has been interrupted."  The front-end also displays a "Refresh Page" button.

**Comment by SebastienDenvil** [comment]
Ok for a short term fix.

**Comment by momipsl** [comment]
Not really much else that can be done as this is a browser specific issue - hence this is the long term solution unless of course I simply try to reestablish the web-socket connection but a few minutes later it will have to be re-established again and so on.

**Comment by SebastienDenvil** [comment]
I believe we miss something. In the sense that when I use twitter or information/sport lives from no disconnection ever occurred. So I doubt this is a browser specific issue. We will devise a long term solution later. But what is clear is that this solution is not the long term solution.

**Comment by momipsl** [comment]
OK let's say a short term solution.  However this issue seems specific to FF under Linux as this does not happen to me when running FF under Mac OS X, however it is certainly possible that this is a false negative and that there is something else under the surface causing the web socket channel to disconnect.

**Comment by SebastienDenvil** [comment]
Close this. The implemented solution is ok for now.

**Comment by SebastienDenvil** [comment]
Front end web-socket connection stay alive.

**Comment by grockland** [comment]
I have the same problem.  The client web-socket connection is being dropped with no notification to or from the server.  When the server breaks no message reaches the client.  But why is the connection being dropped in the first place?  

It is a TCP system like HTTP and the connection is permanent unless one side closes.  Although the HTTP implementation continually drops the connection (inefficiently) the underlying TCP connection allows implementation to remain open as long as desired.  It seems that the Web Socket implementation has taken a little from HTTP and a little from TCP in that it drops after about 3 minutes. It doesn't just respond to the HTML request and drop the underlying TCP connection like HTTP, nor does it seem to allow a non-transient permanent connection like TCP - it is somewhere in-between. 

When the client-side AsyncReceive() drops out a re-Connect sometimes works but not reliably.  In its present state, until the drop-outs and lack of close notification problems are worked out, the system seems non-functional.
