### ISSUE TITLE
Send notification when MQ consumer maps a block to an inactive allocations

### ISSUE THREAD

**Issue by momipsl** [Prodiguer/prodiguer-docs#63]
When the conso MQ consumer maps a conso block to an inactive allocation then the platform will both write to the log and send a notification via email with appropriate subject / content.

**Comment by NeferTiyi** [comment]
Related to this : what should be done if more than one allocation is found? 
This could and probably will happen for tgcc projects because of the short overlap in early January.

**Comment by slipsl** [comment]
Related to this : what should be done if more than one allocation is found?
This could and probably will happen for tgcc projects because of the short overlap in early January.

**Comment by momipsl** [comment]
An inactive allocation notification is now being sent via email.  The email content is defined [here](https://github.com/Prodiguer/prodiguer-server/blob/master/prodiguer_jobs/mq/internal/alert.py#L63-L66).
