### ISSUE TITLE
Verify unique constraint over tbl_consumption

### ISSUE THREAD

**Issue by momipsl** [Prodiguer/prodiguer-docs#64]
Over the tbl_consumption there is a unique constraint over the following fields:

- allocation_id
- sub_project
- login
- date

This unique constraints appears to be not applied when either of these field are null.

**Comment by NeferTiyi** [comment]
More precisely, the unique constraint is not applied because these fields are _nullable_. Wether the actual value is NULL or not doesn't matter.

**Comment by slipsl** [comment]
More precisely, the unique constraint is not applied because these fields are _nullable_. Wether the actual value is NULL or not doesn't matter.

**Comment by momipsl** [comment]
I have added partial indexes so that the null values for the login and sub-project fields trigger a duplicate record exception.  The partial indexes were created as part of the [0.4.4.2 deployment db migration](https://github.com/Prodiguer/prodiguer-shell/blob/master/bash/db/sql/pgres_migrate-0-4-4-2.sql#L112-L115).
