### ISSUE TITLE
Monitoring page cookies to save latest user facets selection

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#67]

**Comment by momipsl** [comment]
A cookie is already used to save the no. of entries displayed in the search grid.  The cookie manager will be extended to also persist the latest user facets.  When the page is refreshed then the filters will be initialised from the cookie unless they are specified as a URL parameter.

**Comment by momipsl** [comment]
The user's latest facet selections are saved to a cookie.  When the user returns to the page the filters are intiialized from the cookie.
