### ISSUE TITLE
Monitoring page persistent URL

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#68]
So that one can send an url to someone with predefined facets selection

**Comment by momipsl** [comment]
Facets will be initialised from URL query parameters.  If a facet is not defined as a URL query parameter then the facet will be initialised from a cookie.

**Comment by momipsl** [comment]
Added permalink buttonnto the front end.  When the user clicks upon the button the permanent URL is displayed.  The search facets are appended to the page URL as query parameters.  

For example:  https://prodiguer-test-web.ipsl.fr/static/simulation.monitoring.html?timeslice=*&activity=ipsl&login=p86denv&state=running
