### ISSUE TITLE
Identify and notify trusting specific messages

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#7]
Currently trusting jobs are not ingested. It's likely due to an ExperimentName not in the CV.

Trusting will use ExperimentName=trusting. Activity_id will be the IPSL one. We could imagine a 'regression test' Experiment_group

Those should be identified and we would send messages or SMS when:
trusting failed or when no trusting related messages were received.

**Comment by momipsl** [comment]
Can you clarify that controlled vocabulary terms will be as follows:  
  activity = ipsl;
  experiment=trusting;
  experiment-group=regression-test;

**Comment by SebastienDenvil** [comment]
yes it will be.

**Comment by momipsl** [comment]
Can you give me more details on this use case as it seems to be one that we can implement now.

**Comment by SebastienDenvil** [comment]
Not ready yet. We need internal brainstorming.

**Comment by momipsl** [comment]
Are the trusting messages now being dispatched by libIGCM ?

**Comment by momipsl** [comment]
I see trusting messages being dispatched by liblIGCM.  Are we ready to start adding trusting related features to the platform?

**Comment by SebastienDenvil** [comment]
That is low priority for the moment

**Comment by SebastienDenvil** [comment]
close for now. This is a minor point;
