### ISSUE TITLE
message 1001 are sent. They now need to be consume

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#70]
https://github.com/Prodiguer/prodiguer-docs/wiki/Monitoring-Message-Dictionary#1001

**Comment by asladeofgreen** [comment]
Consumed at back end, being dispatched over web-socket channel.  Now need to update UI.

**Comment by SebastienDenvil** [comment]
messages are consumed. There is another open issue that concerns the UI
