### ISSUE TITLE
Simulation information display

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#71]
Information from message 1001 should be display having in mind a progress bar:
startDate++++++++++[PeriodDateBegin - PeriodDateEnd]--------------endDate

To be discuss

**Comment by asladeofgreen** [comment]
As job updates are reeceived over web-socket channel then the simulation start-end date columns can displayed progress status.  

When user moves mouse over these columns then progress status detail is displayed.
