### ISSUE TITLE
We need JobName as a facet in hermes.ipsl.upmc.fr

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#73]
This facet must also have auto-completion enabled

**Comment by asladeofgreen** [comment]
The simulation name needs to be filterable as well.  

Can remove Activity column & filter as this is superceded by accounting project.

**Comment by asladeofgreen** [comment]
Have implemented this feature in version 1.0.2.2.  There is no auto-completion on the text box itself as the list of simulations automatically updates as you enter text.

**Comment by SebastienDenvil** [comment]
work as expected.
