### ISSUE TITLE
gencmip6 monitoring endpoints

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#74]
When project=gencmip6 or devcmip6 or *cmip6 the monitoring endpoint must be constructed with "work_thredds" instead of "work" alone:

https://esgf.extra.cea.fr/thredds/fileServer/work_thredds/p86maf/IPSLCM6/DEVT/pdControl/CM605.NOSU-LR-pdCtrl-02/MONITORING/index.html

**Comment by asladeofgreen** [comment]
Need to extend javascript function that derives monitoring endpoints.  Complexity = medium.

**Comment by asladeofgreen** [comment]
This has been implemented.  Awaiting testing.

**Comment by SebastienDenvil** [comment]
dont work for the intermonitoring. need to use work_thredds also for the intermonitoring when project=*cmip6

**Comment by asladeofgreen** [comment]
OK will do this for inter-monitoring as well

**Comment by SebastienDenvil** [comment]
can it be done today so that we can announce the new release?

**Comment by asladeofgreen** [comment]
This has now been implemented & deployed.

**Comment by SebastienDenvil** [comment]
working as expected.
