### ISSUE TITLE
jobSubmissionPath to be displayed in the "simulation detail" page

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#75]
Simulation detail page will include this information. Value will come from libIGCM
With

Submit = jobSubmissionPath
Data = dataArchivePath
Post = postOutputPath
Work = workOutputPath

|=================================================================================
| JobName = NPv5.70PDctrl01            JobID = 5307045                             date : 25/07/16 16:40:54 |
| User    = p86fair                                                 last run.card write : 25/07/16 16:19:29 |
|-----------------------------------------------------------------------------------------------------------|
| Submit  | /ccc/cont003/home/gencmip6/p86fair/IPSLCM6.0.5-LR/config/IPSLCM6/NPv5.70PDctrl01                |
| Data     | /ccc/store/cont003/gencmip6/p86fair/IGCM_OUT/IPSLCM6/PROD/pdControl/NPv5.70PDctrl01             |
| Post     | /ccc/scratch/cont003/gencmip6/p86fair/IGCM_OUT/IPSLCM6/PROD/pdControl/NPv5.70PDctrl01/Out       |
| Work    | /ccc/work/cont003/gencmip6/p86fair/IGCM_OUT/IPSLCM6/PROD/pdControl/NPv5.70PDctrl01              |

**Comment by asladeofgreen** [comment]
Partially dervied from 0000 message.  Add jobSubmissionPath to simulation detail overview tab.

**Comment by SebastienDenvil** [comment]
I have changed the 0000 message content. See https://github.com/Prodiguer/prodiguer-docs/wiki/Monitoring-Message-Dictionary#0000

Only messages coming from libIGCM2.8.2 (to be release soon) will contain the new content

Submit = jobSubmissionPath
Figures = storageSmallPath
Data = archivePath
Work = storagePath
