### ISSUE TITLE
prodiguer-db-restet and db backup 

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#8]
Les backups ne fonctionnent pas car le script utilise le /usr/bin/pg_dump system 8.4 incompatible avec la base 9.3. Il faudrait utiliser /usr/pgsql-9.3/bin/pg_dump.

**Comment by momipsl** [comment]
@SebastienDenvil   The following command needs to be executed so that the correct pg_dump version is picked up by the prodiguer-db-reset script:

        sudo ln -s /usr/pgsql-9.4/bin/pg_dump /usr/bin/pg_dump --force

**Comment by SebastienDenvil** [comment]
It's not good practice to link accros system binaries .... We shall modify the script instead of modifying the system.

**Comment by momipsl** [comment]
I will update the script so that it gets pg_dump path from a config setting.

**Comment by momipsl** [comment]
This has been implemented.  Log onto the db-server and:
     1.  Execute: prodiguer-stack-update-shell
     2.  Add the following to: /opt/prodiguer/ops/config/prodiguer.sh:
            # Path to pg_dump executable.
            declare DB_PGDUMP=/usr/pgsql-9.3/bin/pg_dump

Upon the next execution of prodiguer-db-reset a db backup will be made in /opt/prodiguer/ops/backups/db/[YYYY-MM-DD].
