### ISSUE TITLE
Inconsistent display of job execution state

### ISSUE THREAD

**Issue by asladeofgreen** [Prodiguer/prodiguer-docs#80]
Marie-Alice noted the following:

Voilà une simulation qui s’est bien passé mais qui reste RUNNING. Le message 1100 n’est jamais arrivé?

https://hermes.ipsl.upmc.fr/static/simulation.messages.html?uid=cfc89a41-9c47-443f-9dd3-b3e9f8cecd24

Les Scripts sont là :
/ccc/scratch/cont003/gencmip6/p529tra/IGCM_OUT/IPSLCM6/DEVT/pdControl/CM605.Z0-LR-pdCtrl-01/Out/Script_Output_CM605.Z0-LR-pdCtrl-01.000108.108228

En résumé :
Début du job OK:
- SCRIPT_PID=8551
- set +x
- /bin/ksh -x /tmp/jobstart.8537
- BATCH_NUM_PROC_TOT=557
  Thu Aug 18 07:30:36 CEST 2016
  …
  Fin de job OK :
  2016-08-19 04:58:08 --Debug1--> Submit next job
  IGCM_sys_Cd : /ccc/work/cont003/gencmip6/p529tra/IPSLCM6.0.5-LR/config/IPSLCM6/CM605.Z0-LR-pdCtrl-01
  IGCM_sys_Qsub : /ccc/work/cont003/gencmip6/p529tra/IPSLCM6.0.5-LR/config/IPSLCM6/CM605.Z0-LR-pdCtrl-01/Job_CM605.Z0-LR-pdCtrl-01
  Submitted Batch Session 5606214

Le job suivant a été bien soumis et s’est bien passé aussi.

Sur la séquence de job (en copie d’écran) il manque le message 1100.

**Comment by asladeofgreen** [comment]
The front-end will be updated to reinterpret job status so that receiving a 1000 means that the previous job is never considered RUNNING even if it's 1100 has not been received.

**Comment by asladeofgreen** [comment]
So I have implemented a change to the front-end so that job status will be set to 'COMPLETE' and the job end date set to 'N/A' under the following circumstances:
1. A later compute job has started;
2.  A later post-processing job has started.

I.E. under these circumstances it is assumed that the original issue was resolved and either the simulation restarted or post-processing jobs launched.

**Comment by asladeofgreen** [comment]
@SebastienDenvil: Can you confirm point 2 above, i.e. that if a later post-processing job starts then we can assume that compute jobs are complete.

**Comment by SebastienDenvil** [comment]
@momipsl Only 1. is needed. 2. will lead to misinterpretation.

**Comment by SebastienDenvil** [comment]
Sorry to react lately but the job status is indeed RUNNING and not COMPLETE in some circumstances. We need to receive 0100 to know a simulation is complete.

As long as we receive we continue the business as usual.
1000 - Computing job starts
1001 - Computing job updates
