### ISSUE TITLE
Failure to display job failure correctly

### ISSUE THREAD

**Issue by asladeofgreen** [Prodiguer/prodiguer-docs#81]
Marie-Alice noted the following:

voilà une simulation d’Olivier Boucher qui aurait pu être détectée par le système de heart bit.

Le job est paramétré pour 30 mn. Le job a été tué par le système lors d’un souci sur curie au bout d’une heure. 

Il ne s’est rien passé pendant 24h et l’utilisateur n’a pas reçu d’info.

Le message n° 87 1000 n’a pas été suivi d’un message 1100 dans le temps imparti. Mais les messages 86 et 87 ont mis 22h a être traité : colonne latency.  Ceci explique cela?

Le message 88 montre la relance faite à la main par Olivier.

Voilà la séquence de messages dans une copie d’écran ou disponible là :

https://hermes.ipsl.upmc.fr/static/simulation.messages.html?uid=26c89de4-5e02-446f-99d1-8474d9b1917e

**Comment by asladeofgreen** [comment]
So I have implemented a change to the front-end so that job status will be set to 'COMPLETE' and the job end date set to 'N/A' under the following circumstances:
1. A later compute job has started;
2.  A later post-processing job has started.

I.E. under these circumstances it is assumed that the original issue was resolved and either the simulation restarted or post-processing jobs launched.

**Comment by SebastienDenvil** [comment]
This issue is related to issues 9
https://github.com/Prodiguer/prodiguer-docs/issues/9

If we fix issue 9 we fix issue 81.

None of 1. and 2. should be implemented otherwise we will have big trouble.
