### ISSUE TITLE
Monitoring page timeslice download improvment

### ISSUE THREAD

**Issue by asladeofgreen** [Prodiguer/prodiguer-docs#84]
When a timeslice >= 2M is being pulled from the database, then rendering latency becomes unacceptable.  To reduce such latency the  job information can be downloaded JIT.

We need to consider whether the search/sort fields also need to be passed to the server side or not.  Currently all search state is managed in the front-end ... moving it to the server side will increase network traffic and server-side processing complexity.  On the other hand the front-end code could as a consequence be simplified.

**Comment by SebastienDenvil** [comment]
General comment : simplification on the client side sounds good to me.

The current front end performance is acceptable.
