### ISSUE TITLE
Late job (8000) supervision impacted by end job (1100) arrival latency 

### ISSUE THREAD

**Issue by asladeofgreen** [Prodiguer/prodiguer-docs#86]
Buffering of emails by libIGCM means that 1100 message arrival latency may be several hours.  This impacts upon the supervision of late jobs as its' detection algorithm assumes 1100 message latency is only 5 minutes.  

Therefore one potential solution is to append a maximum latency delta to the job warning delay calculation.  This delta can be derived from max latency of previously received 1000/1001 messages.

**Comment by asladeofgreen** [comment]
This is also potentially being impacted by the suspension of the MQ daemons during deployment upgrades.  We need to distinguish between time of arrival at RabbitMQserver and time of actual processing to avoid calculating incorrect job warning delays.

**Comment by SebastienDenvil** [comment]
Has been implemented rigth?

I tested it and it seems ok.

**Comment by asladeofgreen** [comment]
Yes implemented.  Please test.
