### ISSUE TITLE
Enable heartbeat for simulations

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#9]
If a simulation send the "1000 - Job starts" message but do not send the "1100 - Job ends" message X seconds after then the simulation is at risk. Need to find a color code for the UI (I suggest orange).

The X should be a parameter easily settable. Ideally each simulation will have its own "X value". libIGCM will be able to send it in seconds in a future release.

**Comment by momipsl** [comment]
Just commited changes to support this use case form the backend point of view.  The database table tbl_simulation_state_change has been extended with a job_uid column.  The MQ consumers in-monitoring-1000 & in-monitoring-1100 write timestamped entries in this table.  Therefore it is trivial to find the job's that have not completed within the X seconds timeframe.  

To propogate this to the front-end I will:
  1.  Add a config setting in prodiguer.json to specify the X.
  2.  Push job state changes to the front-end via the web-socket channel;
  3.  Update UI rendering to indicate this either via color-coding or a warning icon.

**Comment by momipsl** [comment]
I have begun the front-end changes for this issue.  I have added a column to the table of simulations: Jobs.  This indicates the number of simulation jobs, i.e. 1 for each '1000 - Job starts' message.  The cell for this value in the table is highlighted red if no "1100 - Job ends" message has been received since X seconds.  The value for X seconds is derived from the prodiguer.json file and I have initialised it to 180.

Not yet committed as I will perform further testing to ensure UI is correctly refreshed when either the new simulation event is received or the simulation state change event is recieved.

**Comment by momipsl** [comment]
UI is correctly dispalying both number of simulations jobs and an indication when a job has not completed within the timeframe specified by libIGCM.

The MQ consumer for message type 1000 has been extended to parse the message content for a new field called jobWarningDelay.  If this field does not exist then it is initialised to the configuration file setting: monitoring.defaultJobWarningDelayInSeconds (currently set to 180 seconds).

**Comment by SebastienDenvil** [comment]
the default should be more like 86400 seconds for monitoring.defaultJobWarningDelayInSeconds

**Comment by momipsl** [comment]
prodiguer.json template has been updated

**Comment by SebastienDenvil** [comment]
You mentionned that the UI will display indication when a job has not completed within the timeframe specified by libIGCM (or the default value). What kind of indications is that?

**Comment by momipsl** [comment]
The job count cell will be coloured red.

**Comment by SebastienDenvil** [comment]
Seems all good. Just need to check the behaviour when a corrective action has been taken and the simulation submitted again. In that case the job count cell should be given a "normal" colour.

**Comment by SebastienDenvil** [comment]
When a job did not completed within the time specified by JobWarningDelay the job count cell turn orange.
But when the job is running again (message 1000) because corrective action has been undertaken, the cell should be given is regular color.

**Comment by SebastienDenvil** [comment]
It's important to have the cell being given his regular color when corrective action has been undertaken. See my previous message.

**Comment by momipsl** [comment]
I will update UI so that the algorithm that decides whether a job is "late" is overridden if a 1000 was received.

**Comment by SebastienDenvil** [comment]
"defaultJobWarningDelayInSeconds" was still set to 180 seconds in prodiguer.json

Do we have any actions to take for messages already ingested? 180 seconds was way too short and the information that is displayed now is misleading.

https://prodiguer-test-web.ipsl.fr/static/simulation.monitoring.one.html?uid=ea33c48a-0219-4bc5-
b48e-a82144c98891

**Comment by SebastienDenvil** [comment]
I updated ops/config/prodiguer.json and set defaultJobWarningDelayInSeconds=86400

**Comment by SebastienDenvil** [comment]
I updated again ops/config/prodiguer.json and set defaultJobWarningDelayInSeconds=86400

**Comment by SebastienDenvil** [comment]
I would like to close that one. But the UI seems to give unreliable information about this. Some jobs are obviously late but the UI do not say anything about it:
https://prodiguer-test-web.ipsl.fr/static/simulation.detail.html?uid=339d48fa-c022-4290-8496-2caa89e837d9

**Comment by momipsl** [comment]
Can you specify which jobs are late and the UI is not saying anything.  I only see one late job (compute-job #13) and the lateness is being reported correctly.

**Comment by SebastienDenvil** [comment]
compute job #8 is suppose to be running since the 15th of March.

**Comment by momipsl** [comment]
OK yes I understand now.  So how should the UI render this situation ?  The lateness value can be assigned and the row highlighted in red / orange ?

**Comment by SebastienDenvil** [comment]
highlighted in orange is a good one. Could turn red after 24 hours of lateness.

**Comment by momipsl** [comment]
Ok sounds good.

**Comment by SebastienDenvil** [comment]
We decided to turn red after 1 hour of lateness.

**Comment by SebastienDenvil** [comment]
What is the status here?

**Comment by asladeofgreen** [comment]
In progress but most of work has been done.  Low hanging fruit at this point.
