### ISSUE TITLE
Change inter-monitoring call

### ISSUE THREAD

**Issue by PBrockmann** [Prodiguer/prodiguer-docs#95]
The inter-monitoring has changed and is now based on pyferret.  The application has been installed on a new server as well.
New features such as dates offset has also been added.

The change requested should be limited as changing
http://webservices.ipsl.fr/monitoring_fromprodiguer
by
http://webservices2017.ipsl.fr/interMonitoring_fromHermes

The code is handled from https://github.com/PBrockmann/interMonitoring/tree/fromHermes

**Comment by asladeofgreen** [comment]
@PBrockmann For clarification:

Currently the HERMES front-end performs an HTTP POST to the following inter-monitoring php script:

  http://webservices.ipsl.jussieu.fr/monitoring_fromprodiguer/index.php

Can you please confirm that HERMES front-end will continue to perform an HTTP POST but to the new script:

  http://webservices2017.ipsl.fr/interMonitoring_fromHermes/index.php

**Comment by PBrockmann** [comment]
Same request.

**Comment by asladeofgreen** [comment]
Ok have implemented change.  Will deploy to HERMES TEST tomorrow.

**Comment by asladeofgreen** [comment]
@PBrockmann: implemented, please test @ https://hermes.ipsl.upmc.fr/static/app.html

**Comment by PBrockmann** [comment]
Hi, 

Cannot test it from home ? 
get a 403 

FYI, I have test the call from 
http://webservices2017.ipsl.fr/interMonitoring_fromHermes/test.php 
so should work the same way. 

Can you ask to Sébastien to test the call from Hermès ? 
Thanks 

Patrick 



De: "Mark A. Greenslade" <notifications@github.com> 
À: "Prodiguer/prodiguer-docs" <prodiguer-docs@noreply.github.com> 
Cc: "Patrick Brockmann" <Patrick.Brockmann@lsce.ipsl.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Mercredi 7 Juin 2017 10:59:43 
Objet: Re: [Prodiguer/prodiguer-docs] Change inter-monitoring call (#95) 



@PBrockmann : implemented, please test @ https://hermes.ipsl.upmc.fr/static/app.html
